var nombre=(prompt("Enter your name"));
var tipo=(prompt("Enter document type"));
var numero=(prompt("Enter your document number"));
var gen=(prompt("biological gender"));
var esta=(prompt("enter your height"));
var life=(prompt("Is it true that I live in Carthage? True or false"));
console.log("Hello my name is: "+ nombre);
console.log("My number from " + tipo + " is: " + numero);
console.log("biological gender "+ gen );
console.log("My height is  "+ esta );
console.log("Is it true that I live in Carthage: "+ life );